objects/Callout_Log__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>copado__Project__c</referenceTo>
        <relationshipLabel>Callout Logs</relationshipLabel>
        <relationshipName>Callout_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response_Body__c</fullName>
        <label>Response Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status_Code__c</fullName>
        <label>Status Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>copado__User_Story__c</referenceTo>
        <relationshipLabel>Callout Logs</relationshipLabel>
        <relationshipName>Callout_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Callout Log</label>
    <nameField>
        <displayFormat>CL-{0000000000}</displayFormat>
        <label>Integration  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Callout Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__User_Story__c.object
<CustomObject>
    <fields>
        <fullName>Enable_Logs__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Logs</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Field_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>copado__Project__c</referenceTo>
        <relationshipLabel>Field Mappings</relationshipLabel>
        <relationshipName>Field_Mappings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salesforce_Field_Name__c</fullName>
        <label>Salesforce Field Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Field_Type__c</fullName>
        <description>Default value is set to string if not selected.</description>
        <label>Target Field Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>string</fullName>
                </value>
                <value>
                    <fullName>object</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Third_Party_Field_Name__c</fullName>
        <label>Third Party Field Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Field Mapping</label>
    <nameField>
        <displayFormat>FM-{0000000000}</displayFormat>
        <label>Field Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Utilities.cls
/**
 * Created by umitcanuckan on 06/06/2018.
 */
//Helper methods
public with sharing class Utilities {
    //callout log list to be inserted as a final action
    public static List<Callout_Log__c> callOutLogList2Insert {get{
        if(null == callOutLogList2Insert){
            callOutLogList2Insert = new List<callout_log__c>();
        }
        return callOutLogList2Insert;
    }set;}
    //http method based on named credential and current parameters
    //projectid and userid parameter are to use on log creation
    public static string MakeCallout(string namedCredential,string firstParam,string secondParam,string firstUrlpart,string secondUrlpart,List<string> additionalHeader,Method methodType,string bodyParam,sObject userStory,sObject project){
        HttpRequest req = new HttpRequest();
        //exp: callout: endpoint + projectExternalId + '/_apis/wit/wiql/' + workspaceId +'?api-version=4.1';
        req.setEndpoint('callout:'+namedCredential+'/'+firstParam+firstUrlpart+secondParam+secondUrlpart);
        for(string ahItem:additionalHeader) {
            req.setHeader(ahItem.split(':')[0], ahItem.split(':')[1]);
        }
        req.setMethod(string.valueOf(methodType));
        if(string.isNotBlank(bodyParam)) {
            req.setBody(bodyParam);
        }
        Http http = new Http();
        HTTPResponse res = http.send(req);
        if(null != userStory && (boolean)userStory.get('enable_logs__c')){
            callOutLogList2Insert.add(new Callout_Log__c(Response_Body__c=res.getBody(),Status__c=res.getStatus(),status_code__c=string.valueof(res.getStatusCode()),User_Story__c = (string)userStory.get('id')));
        }
        else if(null != project && (boolean)project.get('enable_logs__c')){
            callOutLogList2Insert.add(new Callout_Log__c(Response_Body__c=res.getBody(),Status__c=res.getStatus(),status_code__c=string.valueof(res.getStatusCode()),project__c = (string)project.get('id')));
        }
        system.debug('res.getBody()==> '+res.getBody());
        return res.getBody();
    }
    //Map to use on dynamic cast logic
    public static Map<String, Schema.SObjectField> M;
    static {
        M = Schema.SObjectType.copado__User_Story__c.fields.getMap();
    }
    //casts value based on the current sObject field
    public static object returnCastedValue(object param,string fname){
        Schema.SObjectField field = M.get(fname);
        string FldType = string.valueOf(field.getDescribe().getType()).toLowerCase();
        if (FldType == 'textarea' || FldType == 'picklist' || fldType == 'reference') {
            FldType = 'string';
        }
        system.debug('FldType===> '+FldType);
        if(FldType == 'boolean')            return boolean.valueOf(param);
        if(FldType == 'string')             return String.valueOf(param);
        if(FldType == 'blob')               return (blob)param;
        if(FldType == 'date')               return Date.valueOf(param);
        if(FldType == 'datetime')           return Datetime.valueOf(param);
        if(FldType == 'time')               return (time)param;
        if(FldType == 'integer')            return Integer.valueOf(param);
        if(FldType == 'long')               return (long)param;
        if(FldType == 'decimal')            return (decimal)param;
        if(FldType == 'double')             return Double.valueOf(param);
        return null;
    }
    //usermap to match lookup values via third party users' mail addresses
    public static final Map<string,id> userMap;
    static{
        userMap = new Map<string,id>();
        for(user u:[select id,email from user]){
            userMap.put(u.email,u.id);
        }
    }
    //Field mapping values between salesforce and third party platform fields under related project
    public static Map<string,string> returnFieldMap(id pid,string additionalWhereClause){
        Map<string,string> fieldMap;
        if(null == fieldMap){
            fieldMap = new Map<string,string>();
            for(Field_Mapping__c fm:database.query('select Salesforce_Field_Name__c, Third_Party_Field_Name__c from Field_Mapping__c where project__c =: pid ' + additionalWhereClause)){
                fieldMap.put(fm.Salesforce_Field_Name__c.toLowerCase(),fm.Third_Party_Field_Name__c.toLowerCase());
            }
        }
        return fieldMap;
    }
    //returns a map with sf field api name to target field type, (if the target field on the third party program expect string or a json object as a value **** defined by "target field type" field on the field mapping object ****)
    public static Map<string,string> returnTargetTypeMap(id pid,string additionalWhereClause){
        Map<string,string> fieldMap;
        if(null == fieldMap){
            fieldMap = new Map<string,string>();
            for(Field_Mapping__c fm:database.query('select Salesforce_Field_Name__c, Third_Party_Field_Name__c, Target_Field_Type__c from Field_Mapping__c where project__c =: pid ' + additionalWhereClause)){
                fieldMap.put(fm.Salesforce_Field_Name__c.toLowerCase(),(string.isBlank(fm.Target_Field_Type__c) ? '' : fm.Target_Field_Type__c.toLowerCase()));
            }
        }
        return fieldMap;
    }
    public static string replaceFromCurly(string strwcurly){
         return strwcurly.replace('lcurly','{').replace('rcurly','}');
    }
    //method to create logs under related user story or project record based on the step of the integration after all callouts are done
    public static void createLogRecords(){
        if(callOutLogList2Insert.size() > 0) {
            database.insert(callOutLogList2Insert, false);
        }
    }
}