objects/copado__Project__c.object
<CustomObject>
    <fields>
        <fullName>Copado_Integration_Setting__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Copado Integration Setting</label>
        <referenceTo>Copado_Integration_Setting__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enable_Logs__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Logs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_External_Id__c</fullName>
        <label>Project External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Workspace_Id__c</fullName>
        <label>Workspace Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Copado_Integration_Setting__c.object
<CustomObject>
    <fields>
        <fullName>External_System__c</fullName>
        <label>External System</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Visual Studio Team Services</fullName>
                </value>
                <value>
                    <fullName>JIRA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Named_Credential__c</fullName>
        <label>Named Credential</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Copado Integration Setting</label>
    <nameField>
        <label>Copado Integration Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Copado Integration Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ScheduleUserStoryFetch.cls
/**
 * Created by umitcanuckan on 07/06/2018.
 */


global class ScheduleUserStoryFetch Implements Schedulable
{
    copado__project__c cpRecord;
    public ScheduleUserStoryFetch(id pId){
        cpRecord = [select id,name, Copado_Integration_Setting__r.External_System__c, Copado_Integration_Setting__r.Named_Credential__c,enable_logs__c, Project_External_Id__c, workspace_id__c from copado__project__c where id=:pId];
    }

    global void execute(SchedulableContext sc)
    {
        Database.executeBatch(new ExecuteUserStoryUpsert(this.cpRecord),200);
    }
}