objects/copado__Project__c.object
<CustomObject>
    <fields>
        <fullName>Copado_Integration_Setting__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Copado Integration Setting</label>
        <referenceTo>Copado_Integration_Setting__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_External_Id__c</fullName>
        <label>Project External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Workspace_Id__c</fullName>
        <label>Workspace Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/copado__User_Story__c.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Copado_Integration_Setting__c.object
<CustomObject>
    <fields>
        <fullName>External_System__c</fullName>
        <label>External System</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Visual Studio Team Services</fullName>
                </value>
                <value>
                    <fullName>JIRA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Named_Credential__c</fullName>
        <label>Named Credential</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Copado Integration Setting</label>
    <nameField>
        <label>Copado Integration Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Copado Integration Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UserStoryHandler.cls
public class UserStoryHandler{
    
    @InvocableMethod(label='Call Factory 4 Third Party Update' description='Calls Integration Factory to make callout')
    public static void callFactory4ThirdPartyUpdate(List<copado__user_story__c> usRecords) {
        set<id> usIds = new set<id>();
        for(copado__user_story__c us:usRecords){
            usIds.add(us.id);
        }
        if(!System.isFuture() && !System.isBatch()) {
            callFactory4ThirdPartyUpdate(usIds);
        }
    } 
    @future(callout=true)
    public static void callFactory4ThirdPartyUpdate(set<id> usIds){
        List<copado__user_story__c> userStoryList = [select id,external_id__c,copado__project__c,copado__project__r.Project_External_Id__c,copado__project__r.workspace_id__c,copado__project__r.Copado_Integration_Setting__r.External_System__c,copado__Project__r.Copado_Integration_Setting__r.Named_Credential__c from copado__user_story__c where id in:usIds and copado__project__c != null and copado__Project__r.Copado_Integration_Setting__c != null and external_id__c != null];
        for(copado__user_story__c usItem:userStoryList){
            IntegrationFactory.returnInstance(usItem.copado__project__r.Copado_Integration_Setting__r.External_System__c).updateRecord(usItem);
        }
    }
}